### ISSUE TITLE
Topology 

### ISSUE THREAD

**Issue by gedw99** [lunabrain-ai/lunabrain#14]
This looks nice and extensible

there is or is not a db dependency ?

saw it’s commented out and wanted to know the plan.

is the db used to hol the links to where stuff is out ? Just a guess ..

I have been using data fusion / golang and minio as a data lane that is searchable. 

Anyways just want to know as I am curious if I can work on this code bsse too.

**Comment by breadchris** [comment]
There is a db dependency. All actions that affect the database are currently in https://github.com/lunabrain-ai/lunabrain/blob/main/pkg/store/db/db.go#L28 (kind of an anti-pattern, but i had it like this for simplicity).

There are some calls into this in the process content pipeline, such as here https://github.com/lunabrain-ai/lunabrain/blob/main/pkg/pipeline/workflow.go#L93.

Is there something that you were looking to do? We are still trying to figure out what the API should look like for calling to lunabrain, if there are maybe specific things you want to be able to do.
